### ISSUE TITLE
Program se ne kompajlira

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-046-bilijar#1]

**Comment by chokaa** [comment]
Ja sam na poslu do 5, cim dodjem kuci cu da probam/proverim ponovo ali kod mene radi program, juce sam slucajno umesto bilijar.c fajla upload i izvrsni fajl bilijar pa probajte s tim da li mozete da pokrenete ?

**Comment by ivan-cukic-matf** [comment]
Sve je u redu, skripta nije povukla poslednju verziju
